/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu.GUI;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlynhansu.Model.BaoHiem;
import quanlynhansu.Model.NhanVien;
import quanlynhansu.Model.PhuCap;
import quanlynhansu.Model.ThuongPhat;
import quanlynhansu.DAO.BaoHiemDAO;
import quanlynhansu.DAO.NhanVienDAO;
import quanlynhansu.DAO.PhuCapDAO;
import quanlynhansu.DAO.ThuongPhatDAO;

/**
 *
 * @author Acer
 */
public class FrmCheDo extends javax.swing.JInternalFrame {

    ArrayList<BaoHiem> listbh = new ArrayList<>();
    ArrayList<NhanVien> listnv = new ArrayList<>();
    ArrayList<PhuCap> listpc = new ArrayList<>();
    ArrayList<ThuongPhat> listtp = new ArrayList<>();

    BaoHiemDAO bhdao = new BaoHiemDAO();
    PhuCapDAO pcdao = new PhuCapDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    ThuongPhatDAO tpdao = new ThuongPhatDAO();
    DefaultTableModel modelBH, modelPC, modelTP;
    DefaultComboBoxModel modelManvBH, modelManvPC, modelManvTP;
    Date date, date1;
    ThuongPhat tp = new ThuongPhat();
    BaoHiem bh = new BaoHiem();
    PhuCap pc = new PhuCap();

    /**
     * Creates new form FrmCheDo
     */
    public FrmCheDo() {
        initComponents();
        loadBH();
        loadPC();
        loadTP();
        loadcbxMaNVBH();
        loadcbxMaNVPC();
        loadcbxMaNVTP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBaohiem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxMaNVBaoHiem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtLoaiBH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSotheBH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateNgayCapBH = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        dateNgayHetHanBH = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        txtNoiCapBH = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtGhiChuBH = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtBHSearch = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnXoaBH = new javax.swing.JButton();
        btnSuaBH = new javax.swing.JButton();
        btnThemBH = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPhuCap = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbxMaNVPhuCap = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtLoaiPhuCap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dateTuNgayPC = new org.jdesktop.swingx.JXDatePicker();
        txtTienPhuCap = new javax.swing.JTextField();
        dateDenNgayPC = new org.jdesktop.swingx.JXDatePicker();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtGhiChuPC = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtPCSearch = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnThemPC = new javax.swing.JButton();
        btnSuaPC = new javax.swing.JButton();
        btnXoaPC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        cbxMaNvThuongPhat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLoaiThuongPhat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTienThuongPhat = new javax.swing.JTextField();
        txtLyDoThuongPhat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dateNgayThuongPhat = new org.jdesktop.swingx.JXDatePicker();
        jLabel19 = new javax.swing.JLabel();
        txtGhiChuThuongPhat = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        txtTPSearch = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbThuongPhat = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnThemThuongPhat = new javax.swing.JButton();
        btnSuaThuongPhat = new javax.swing.JButton();
        btnXoaThuongPhat = new javax.swing.JButton();

        setTitle("Chế độ");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbBaohiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbBaohiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Loại bảo hiểm", "Số thẻ BH", "Ngày cấp", "Ngày hết hạn", "Nơi cấp", "Ghichu"
            }
        ));
        tbBaohiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBaohiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBaohiem);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên ");

        cbxMaNVBaoHiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Loại bảo hiểm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số thẻ BH");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày cấp");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày hết hạn");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nơi cấp");

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setText("Ghi chú");

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtBHSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBHSearch.setText("Tìm theo mã nhân viên or số thẻ BH");
        txtBHSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBHSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBHSearchMouseExited(evt);
            }
        });
        txtBHSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBHSearchActionPerformed(evt);
            }
        });
        txtBHSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBHSearchKeyReleased(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBHSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBHSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMaNVBaoHiem, 0, 128, Short.MAX_VALUE)
                    .addComponent(txtSotheBH)
                    .addComponent(txtLoaiBH))
                .addGap(130, 130, 130)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNgayHetHanBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgayCapBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiCapBH, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtGhiChuBH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateNgayCapBH, dateNgayHetHanBH, txtGhiChuBH, txtNoiCapBH});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxMaNVBaoHiem, txtLoaiBH, txtSotheBH});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxMaNVBaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(dateNgayCapBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtGhiChuBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtLoaiBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dateNgayHetHanBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoiCapBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtSotheBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxMaNVBaoHiem, txtLoaiBH, txtSotheBH});

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXoaBH.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnXoaBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-delete-30.png"))); // NOI18N
        btnXoaBH.setText("Xóa");
        btnXoaBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBHActionPerformed(evt);
            }
        });

        btnSuaBH.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnSuaBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-edit-property-30.png"))); // NOI18N
        btnSuaBH.setText("Sửa ");
        btnSuaBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaBHActionPerformed(evt);
            }
        });

        btnThemBH.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnThemBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-add-property-30.png"))); // NOI18N
        btnThemBH.setText("Thêm");
        btnThemBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnThemBH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaBH)
                .addGap(263, 263, 263)
                .addComponent(btnXoaBH)
                .addGap(98, 98, 98))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSuaBH, btnThemBH, btnXoaBH});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemBH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSuaBH, btnThemBH, btnXoaBH});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bảo hiểm", jPanel1);

        tbPhuCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Loại phụ cấp", "Tiền phụ cấp", "Từ ngày", "Đến ngày", "Ghi chú"
            }
        ));
        tbPhuCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhuCapMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbPhuCap);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setPreferredSize(new java.awt.Dimension(1075, 186));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mã nhân viên");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Loại phụ cấp");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tiền phụ cấp");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Từ ngày ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Đến ngày");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Ghi chú");

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtPCSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPCSearch.setText("Tìm theo mã nhân viên or Loại PC");
        txtPCSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPCSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPCSearchMouseExited(evt);
            }
        });
        txtPCSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPCSearchActionPerformed(evt);
            }
        });
        txtPCSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPCSearchKeyReleased(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPCSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtPCSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMaNVPhuCap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLoaiPhuCap)
                    .addComponent(txtTienPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(dateTuNgayPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(402, 402, 402))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateDenNgayPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGhiChuPC, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxMaNVPhuCap, dateDenNgayPC, dateTuNgayPC, txtGhiChuPC, txtLoaiPhuCap, txtTienPhuCap});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(dateTuNgayPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(cbxMaNVPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtLoaiPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(dateDenNgayPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtTienPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtGhiChuPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxMaNVPhuCap, dateDenNgayPC, dateTuNgayPC, txtGhiChuPC, txtLoaiPhuCap, txtTienPhuCap});

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThemPC.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnThemPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-add-property-30.png"))); // NOI18N
        btnThemPC.setText("Thêm ");
        btnThemPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPCActionPerformed(evt);
            }
        });

        btnSuaPC.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnSuaPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-edit-property-30.png"))); // NOI18N
        btnSuaPC.setText("Sửa ");
        btnSuaPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPCActionPerformed(evt);
            }
        });

        btnXoaPC.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnXoaPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-delete-30.png"))); // NOI18N
        btnXoaPC.setText("Xóa");
        btnXoaPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnThemPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaPC)
                .addGap(195, 195, 195)
                .addComponent(btnXoaPC)
                .addGap(114, 114, 114))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSuaPC, btnThemPC, btnXoaPC});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemPC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSuaPC)
                        .addComponent(btnXoaPC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSuaPC, btnThemPC, btnXoaPC});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phụ Cấp", jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setPreferredSize(new java.awt.Dimension(1075, 187));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mã nhân viên");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Loại ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tiền ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Lý do");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Ngày");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Ghi chú");

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtTPSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTPSearch.setText("Tìm theo mã nhân viên or loại");
        txtTPSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTPSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTPSearchMouseExited(evt);
            }
        });
        txtTPSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPSearchActionPerformed(evt);
            }
        });
        txtTPSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTPSearchKeyReleased(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTPSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtTPSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMaNvThuongPhat, 0, 124, Short.MAX_VALUE)
                    .addComponent(txtLoaiThuongPhat)
                    .addComponent(txtTienThuongPhat))
                .addGap(137, 137, 137)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(46, 46, 46)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNgayThuongPhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLyDoThuongPhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtGhiChuThuongPhat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxMaNvThuongPhat, dateNgayThuongPhat, txtGhiChuThuongPhat, txtLoaiThuongPhat, txtLyDoThuongPhat, txtTienThuongPhat});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMaNvThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtLoaiThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTienThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChuThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(dateNgayThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLyDoThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel19)))))
                .addGap(18, 18, 18))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxMaNvThuongPhat, dateNgayThuongPhat, txtGhiChuThuongPhat, txtLoaiThuongPhat, txtLyDoThuongPhat, txtTienThuongPhat});

        tbThuongPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Loại", "Tiền", "Lý do", "Ngày", "Ghi chú"
            }
        ));
        tbThuongPhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThuongPhatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbThuongPhat);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThemThuongPhat.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnThemThuongPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-add-property-30.png"))); // NOI18N
        btnThemThuongPhat.setText("Thêm ");
        btnThemThuongPhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemThuongPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuongPhatActionPerformed(evt);
            }
        });

        btnSuaThuongPhat.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnSuaThuongPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-edit-property-30.png"))); // NOI18N
        btnSuaThuongPhat.setText("Sửa");
        btnSuaThuongPhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaThuongPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThuongPhatActionPerformed(evt);
            }
        });

        btnXoaThuongPhat.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnXoaThuongPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-delete-30.png"))); // NOI18N
        btnXoaThuongPhat.setText("Xóa ");
        btnXoaThuongPhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaThuongPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuongPhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnThemThuongPhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaThuongPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247)
                .addComponent(btnXoaThuongPhat)
                .addGap(118, 118, 118))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSuaThuongPhat, btnThemThuongPhat, btnXoaThuongPhat});

        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSuaThuongPhat)
                        .addComponent(btnXoaThuongPhat))
                    .addComponent(btnThemThuongPhat, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSuaThuongPhat, btnThemThuongPhat, btnXoaThuongPhat});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thưởng phạt", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//--------------------Bảo hiểm------------------
    private void btnSuaBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaBHActionPerformed
        // TODO add your handling code here:
        if (checkformBH() == true) {
            updateBH();
            loadBH();
        }
    }//GEN-LAST:event_btnSuaBHActionPerformed

    private void tbBaohiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBaohiemMouseClicked
        // TODO add your handling code here:
        displayBH();
    }//GEN-LAST:event_tbBaohiemMouseClicked

    private void btnThemBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBHActionPerformed
        // TODO add your handling code here:
        if (checkformBH() == true) {
            insertBH();
            loadBH();
        }
    }//GEN-LAST:event_btnThemBHActionPerformed

    private void btnXoaBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBHActionPerformed
        // TODO add your handling code here:
        deleteBH();
        loadBH();
    }//GEN-LAST:event_btnXoaBHActionPerformed
//--------------------Phụ cấp------------------

    private void tbPhuCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhuCapMouseClicked
        // TODO add your handling code here:

        displayPC();
    }//GEN-LAST:event_tbPhuCapMouseClicked

    private void btnThemPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPCActionPerformed
        // TODO add your handling code here:
        if (checkformPC() == true) {
            insertPC();
            loadPC();
        }
    }//GEN-LAST:event_btnThemPCActionPerformed

    private void btnSuaPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPCActionPerformed
        // TODO add your handling code here:
        if (checkformPC() == true) {
            updatePC();
            loadPC();
        }
    }//GEN-LAST:event_btnSuaPCActionPerformed

    private void btnXoaPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPCActionPerformed
        // TODO add your handling code here:
        deletePC();
        loadPC();
    }//GEN-LAST:event_btnXoaPCActionPerformed

//----------------------Thưởng phạt---------------
    private void tbThuongPhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThuongPhatMouseClicked
        // TODO add your handling code here:
        displayTP();
    }//GEN-LAST:event_tbThuongPhatMouseClicked

    private void btnThemThuongPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuongPhatActionPerformed
        // TODO add your handling code here:
        if (checkformTP() == true) {
            insertTP();
            loadTP();
        }
    }//GEN-LAST:event_btnThemThuongPhatActionPerformed

    private void btnSuaThuongPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThuongPhatActionPerformed
        // TODO add your handling code here:
        if (checkformTP() == true) {
            updateTP();
            loadTP();
        }
    }//GEN-LAST:event_btnSuaThuongPhatActionPerformed

    private void btnXoaThuongPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuongPhatActionPerformed
        // TODO add your handling code here:

        deleteTP();
        loadTP();


    }//GEN-LAST:event_btnXoaThuongPhatActionPerformed

    private void txtBHSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBHSearchMouseClicked
        // TODO add your handling code here:
        txtBHSearch.setText("");
    }//GEN-LAST:event_txtBHSearchMouseClicked

    private void txtBHSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBHSearchActionPerformed
        // TODO add your handling code here:
        txtBHSearch.setText(null);
    }//GEN-LAST:event_txtBHSearchActionPerformed

    private void txtBHSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBHSearchKeyReleased
        if (!txtBHSearch.getText().isEmpty()) {
            loadSearchBH();
        } else {
            loadBH();
        }
    }//GEN-LAST:event_txtBHSearchKeyReleased

    private void txtPCSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPCSearchMouseClicked
        // TODO add your handling code here:
        txtPCSearch.setText("");
    }//GEN-LAST:event_txtPCSearchMouseClicked

    private void txtPCSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPCSearchActionPerformed
        // TODO add your handling code here:
        txtPCSearch.setText(null);
    }//GEN-LAST:event_txtPCSearchActionPerformed

    private void txtPCSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCSearchKeyReleased
        // TODO add your handling code here:
        if (!txtPCSearch.getText().isEmpty()) {
            loadSearchPC();
        } else {
            loadPC();
        }
    }//GEN-LAST:event_txtPCSearchKeyReleased

    private void txtTPSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTPSearchMouseClicked
        // TODO add your handling code here:
        txtTPSearch.setText(null);
    }//GEN-LAST:event_txtTPSearchMouseClicked

    private void txtTPSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPSearchActionPerformed
        // TODO add your handling code here:
        txtTPSearch.setText(null);

    }//GEN-LAST:event_txtTPSearchActionPerformed

    private void txtTPSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTPSearchKeyReleased
        // TODO add your handling code here:
        if (!txtTPSearch.getText().isEmpty()) {
            loadSearchTP();
        } else {
            loadTP();
        }
    }//GEN-LAST:event_txtTPSearchKeyReleased

    private void txtBHSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBHSearchMouseExited
        // TODO add your handling code here:
        txtBHSearch.setText("Tìm theo mã nhân viên or số thẻ BH");
    }//GEN-LAST:event_txtBHSearchMouseExited

    private void txtPCSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPCSearchMouseExited
        // TODO add your handling code here:
        txtPCSearch.setText("Tìm theo mã nhân viên or Loại PC");
    }//GEN-LAST:event_txtPCSearchMouseExited

    private void txtTPSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTPSearchMouseExited
        // TODO add your handling code here:
        txtTPSearch.setText("Tìm theo mã nhân viên or loại");
    }//GEN-LAST:event_txtTPSearchMouseExited

//load mã nhân viên ra combobox 
    private void loadcbxMaNVBH() {
        modelManvBH = (DefaultComboBoxModel) cbxMaNVBaoHiem.getModel();
        listnv = nvdao.load();
        for (NhanVien nv : listnv) {
            modelManvBH.addElement(nv.getMaNhanVien());
        }
        cbxMaNVBaoHiem.setModel(modelManvBH);
    }

    private void loadcbxMaNVPC() {
        modelManvPC = (DefaultComboBoxModel) cbxMaNVPhuCap.getModel();
        listnv = nvdao.load();
        for (NhanVien nv : listnv) {
            modelManvPC.addElement(nv.getMaNhanVien());
        }
        cbxMaNVPhuCap.setModel(modelManvPC);
    }

    private void loadcbxMaNVTP() {
        modelManvTP = (DefaultComboBoxModel) cbxMaNvThuongPhat.getModel();
        listnv = nvdao.load();
        for (NhanVien nv : listnv) {
            modelManvTP.addElement(nv.getMaNhanVien());
        }
        cbxMaNvThuongPhat.setModel(modelManvTP);
    }

    // -----------------------Bảo hiểm----------------
    private boolean checkformBH() {
        if (txtLoaiBH.getText().equals("")) {
            txtLoaiBH.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã phòng ban", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!(txtSotheBH.getText().matches(".*[a-zA-Z0-9].*"))) {
            txtSotheBH.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Số thẻ bảo hiểm không có kí tự đặc biệt", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (txtNoiCapBH.getText().equals("")) {
            txtNoiCapBH.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập nơi cấp", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadBH() {
        listbh = bhdao.load();
        modelBH = (DefaultTableModel) tbBaohiem.getModel();
        modelBH.setRowCount(0);
        for (BaoHiem nv : listbh) {
            modelBH.addRow(new Object[]{
                nv.getMaNhanVien(),
                nv.getLoaiBaoHiem(),
                nv.getSoThe(),
                nv.getNgayCap(),
                nv.getNgayHetHan(),
                nv.getNoiCap(),
                nv.getGhiChu(),});
        }
    }

    //click vào table hiển thị dữ liệu ra jtextfiled,combobox,jdate Bảng Bảo Hiểm
    private void displayBH() {
        try {
            int current = tbBaohiem.getSelectedRow();
            bh = listbh.get(current);
            cbxMaNVBaoHiem.setSelectedItem(tbBaohiem.getModel().getValueAt(current, 0));
            txtLoaiBH.setText(tbBaohiem.getModel().getValueAt(current, 1).toString());
            txtSotheBH.setText((String) tbBaohiem.getModel().getValueAt(current, 2));
            txtNoiCapBH.setText((String) tbBaohiem.getModel().getValueAt(current, 5));
            txtGhiChuBH.setText((String) tbBaohiem.getModel().getValueAt(current, 6));
            modelBH = (DefaultTableModel) tbBaohiem.getModel();
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) modelBH.getValueAt(current, 3));
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) modelBH.getValueAt(current, 4));
            dateNgayCapBH.setDate(date);
            dateNgayHetHanBH.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(FrmCheDo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void insertBH() {
        try {
            bh.setMaNhanVien(cbxMaNVBaoHiem.getSelectedItem().toString());
            bh.setLoaiBaoHiem(txtLoaiBH.getText());
            bh.setSoThe(txtSotheBH.getText());
            try {
                date = dateNgayCapBH.getDate();
                date1 = dateNgayCapBH.getDate();

                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                bh.setNgayCap(df);
                bh.setNgayHetHan(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            bh.setNoiCap(txtNoiCapBH.getText());
            bh.setGhiChu(txtGhiChuBH.getText());
            BaoHiemDAO bhDao = new BaoHiemDAO();
            if (bhDao.insert(bh) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm bảo hiểm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNVBaoHiem.getSelectedItem().toString() + " ] đã tồn tại không thể thêm");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void updateBH() {
        try {
            bh.setMaNhanVien(cbxMaNVBaoHiem.getSelectedItem().toString());
            bh.setLoaiBaoHiem(txtLoaiBH.getText());
            bh.setSoThe(txtSotheBH.getText());
            try {
                date = dateNgayCapBH.getDate();
                date1 = dateNgayCapBH.getDate();

                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                bh.setNgayCap(df);
                bh.setNgayHetHan(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            bh.setNoiCap(txtNoiCapBH.getText());
            bh.setGhiChu(txtGhiChuBH.getText());
            BaoHiemDAO bhDao = new BaoHiemDAO();
            if (bhDao.update(bh) > 0) {
                JOptionPane.showMessageDialog(null, "Sửa bảo hiểm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNVBaoHiem.getSelectedItem().toString() + " ]  không thể sửa");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void deleteBH() {
        int index = tbBaohiem.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 bảo hiểm trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
        if (tk == JOptionPane.YES_OPTION) {
            if (bhdao.delete(cbxMaNVBaoHiem.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Xóa Bảo Hiểm thành công", "Thông Báo", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
            }

        }
    }
//Serach    

    private void loadSearchBH() {
        listbh = bhdao.Search(txtBHSearch.getText());
        modelBH = (DefaultTableModel) tbBaohiem.getModel();
        modelBH.setRowCount(0);
        for (BaoHiem bh : listbh) {
            modelBH.addRow(new Object[]{
                bh.getMaNhanVien(),
                bh.getLoaiBaoHiem(),
                bh.getSoThe(),
                bh.getNoiCap(),
                bh.getNgayHetHan(),
                bh.getNoiCap(),
                bh.getGhiChu(),});
        }
    }
// -------------------phu cap

    private boolean checkformPC() {
        if (txtLoaiPhuCap.getText().equals("")) {
            txtLoaiBH.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập loại phụ cấp", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!(txtTienPhuCap.getText().matches(".*[0-9].*"))) {
            txtTienPhuCap.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Tiền phụ cấp phải là số ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadPC() {
        listpc = pcdao.load();
        modelPC = (DefaultTableModel) tbPhuCap.getModel();
        modelPC.setRowCount(0);
        for (PhuCap nv : listpc) {
            modelPC.addRow(new Object[]{
                nv.getMaNhanVien(),
                nv.getLoaiPC(),
                nv.getTienPC(),
                nv.getTuNgay(),
                nv.getDenNgay(),
                nv.getGhichu(),});
        }
    }
    //click vào table hiển thị dữ liệu ra jtextfiled,combobox,jdate Bảng Phụ Cấp

    private void displayPC() {
        try {
            int current = tbPhuCap.getSelectedRow();
            pc = listpc.get(current);
            cbxMaNVPhuCap.setSelectedItem(tbPhuCap.getModel().getValueAt(current, 0));
            txtLoaiPhuCap.setText(tbPhuCap.getModel().getValueAt(current, 1).toString());
            txtTienPhuCap.setText(tbPhuCap.getModel().getValueAt(current, 2).toString());
            txtGhiChuPC.setText((String) tbPhuCap.getModel().getValueAt(current, 5));
            modelBH = (DefaultTableModel) tbPhuCap.getModel();
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) modelBH.getValueAt(current, 3));
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) modelBH.getValueAt(current, 4));
            dateTuNgayPC.setDate(date);
            dateDenNgayPC.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(FrmCheDo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
//Thêm phụ cấp

    private void insertPC() {
        try {
            pc.setMaNhanVien(cbxMaNVPhuCap.getSelectedItem().toString());
            pc.setLoaiPC(txtLoaiPhuCap.getText());
            pc.setTienPC(Integer.parseInt(txtTienPhuCap.getText()));
            try {
                date = dateTuNgayPC.getDate();
                date1 = dateDenNgayPC.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                pc.setTuNgay(df);
                pc.setDenNgay(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            pc.setGhichu(txtGhiChuPC.getText());
            if (pcdao.insert(pc) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm phụ cấp thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNVBaoHiem.getSelectedItem().toString() + " ] đã tồn tại không thể thêm");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
// Sửa phụ cấp

    private void updatePC() {
        try {
            pc.setMaNhanVien(cbxMaNVPhuCap.getSelectedItem().toString());
            pc.setLoaiPC(txtLoaiPhuCap.getText());
            pc.setTienPC(Integer.parseInt(txtTienPhuCap.getText()));
            try {
                date = dateTuNgayPC.getDate();
                date1 = dateDenNgayPC.getDate();

                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                pc.setTuNgay(df);
                pc.setDenNgay(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            pc.setGhichu(txtGhiChuPC.getText());
            if (pcdao.update(pc) > 0) {
                JOptionPane.showMessageDialog(null, "Sửa phụ cấp thành công ");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNVPhuCap.getSelectedItem().toString() + " ]  không thể sửa");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
//Xóa Phụ cấp

    private void deletePC() {
        int index = tbPhuCap.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 phụ cấp trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
        if (tk == JOptionPane.YES_OPTION) {
            if (pcdao.delete(cbxMaNVPhuCap.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Xóa phụ cấp thành công", "Thông Báo", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
            }
        }
    }

    public void loadSearchPC() {
        listpc = pcdao.Search(txtPCSearch.getText());
        modelPC = (DefaultTableModel) tbPhuCap.getModel();
        modelPC.setRowCount(0);
        for (PhuCap pc : listpc) {
            modelPC.addRow(new Object[]{
                pc.getMaNhanVien(),
                pc.getLoaiPC(),
                pc.getTienPC(),
                pc.getTuNgay(),
                pc.getDenNgay(),
                pc.getGhichu(),});
        }
    }

    /// ------------Thưởng phạt---------------------
    private boolean checkformTP() {
        if (txtLoaiThuongPhat.getText().equals("")) {
            txtLoaiThuongPhat.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập loại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (txtLyDoThuongPhat.getText().equals("")) {
            txtLyDoThuongPhat.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập lý do", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;

        } else if (!(txtTienThuongPhat.getText().matches(".*[0-9].*"))) // đoạn này em sử dụng biểu thức chính quy của java để kiểm tra nhập vào chỉ là số
        {
            txtTienThuongPhat.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập số cho mục tiền", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadTP() {
        listtp = tpdao.load();
        modelTP = (DefaultTableModel) tbThuongPhat.getModel();
        modelTP.setRowCount(0);
        for (ThuongPhat tp : listtp) {
            modelTP.addRow(new Object[]{
                tp.getMaNhanVien(),
                tp.getLoaiTP(),
                tp.getTien(),
                tp.getLydo(),
                tp.getNgay(),
                tp.getGhichu(),});
        }
    }
    //click vào table hiển thị dữ liệu ra jtextfiled,combobox,jdate Bảng Thưởng phạt

    private void displayTP() {
        try {
            int current = tbThuongPhat.getSelectedRow();
            tp = listtp.get(current);
            cbxMaNvThuongPhat.setSelectedItem(tbThuongPhat.getModel().getValueAt(current, 0));
            txtLoaiThuongPhat.setText(tbThuongPhat.getModel().getValueAt(current, 1).toString());
            txtTienThuongPhat.setText(tbThuongPhat.getModel().getValueAt(current, 2).toString());
            txtLyDoThuongPhat.setText(tbThuongPhat.getModel().getValueAt(current, 3).toString());
            txtGhiChuThuongPhat.setText((String) tbThuongPhat.getModel().getValueAt(current, 5));
            modelTP = (DefaultTableModel) tbThuongPhat.getModel();
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) modelBH.getValueAt(current, 4));
            dateNgayThuongPhat.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(FrmCheDo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Thêm cho bảng thưởng phạt

    private void insertTP() {
        try {
            tp.setMaNhanVien(cbxMaNvThuongPhat.getSelectedItem().toString());
            tp.setLoaiTP(txtLoaiThuongPhat.getText());
            tp.setTien(Integer.parseInt(txtTienThuongPhat.getText()));
            try {
                date = dateNgayThuongPhat.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                tp.setNgay(df);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            tp.setGhichu(txtGhiChuThuongPhat.getText());
            if (tpdao.insert(tp) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thưởng phạt thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNvThuongPhat.getSelectedItem().toString() + " ] đã tồn tại không thể thêm");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void updateTP() {
        try {
            tp.setMaNhanVien(cbxMaNvThuongPhat.getSelectedItem().toString());
            tp.setLoaiTP(txtLoaiThuongPhat.getText());
            tp.setTien(Integer.parseInt(txtTienThuongPhat.getText()));
            try {
                date = dateNgayThuongPhat.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                tp.setNgay(df);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            tp.setGhichu(txtGhiChuThuongPhat.getText());
            if (tpdao.update(tp) > 0) {
                JOptionPane.showMessageDialog(null, "Sửa thưởng phạt thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNvThuongPhat.getSelectedItem().toString() + " ]  không thể sửa");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void deleteTP() {
        int index = tbThuongPhat.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 phụ cấp trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
        if (tk == JOptionPane.YES_OPTION) {
            if (tpdao.delete(cbxMaNvThuongPhat.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Xóa thưởng phạt thành công", "Thông Báo", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
            }
        }
    }

    private void loadSearchTP() {
        listtp = tpdao.Search(txtTPSearch.getText());
        modelTP = (DefaultTableModel) tbThuongPhat.getModel();
        modelTP.setRowCount(0);
        for (ThuongPhat tp : listtp) {
            modelTP.addRow(new Object[]{
                tp.getMaNhanVien(),
                tp.getLoaiTP(),
                tp.getTien(),
                tp.getLydo(),
                tp.getNgay(),
                tp.getGhichu(),});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaBH;
    private javax.swing.JButton btnSuaPC;
    private javax.swing.JButton btnSuaThuongPhat;
    private javax.swing.JButton btnThemBH;
    private javax.swing.JButton btnThemPC;
    private javax.swing.JButton btnThemThuongPhat;
    private javax.swing.JButton btnXoaBH;
    private javax.swing.JButton btnXoaPC;
    private javax.swing.JButton btnXoaThuongPhat;
    private javax.swing.JComboBox<String> cbxMaNVBaoHiem;
    private javax.swing.JComboBox<String> cbxMaNVPhuCap;
    private javax.swing.JComboBox<String> cbxMaNvThuongPhat;
    private org.jdesktop.swingx.JXDatePicker dateDenNgayPC;
    private org.jdesktop.swingx.JXDatePicker dateNgayCapBH;
    private org.jdesktop.swingx.JXDatePicker dateNgayHetHanBH;
    private org.jdesktop.swingx.JXDatePicker dateNgayThuongPhat;
    private org.jdesktop.swingx.JXDatePicker dateTuNgayPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbBaohiem;
    private javax.swing.JTable tbPhuCap;
    private javax.swing.JTable tbThuongPhat;
    private javax.swing.JTextField txtBHSearch;
    private javax.swing.JTextField txtGhiChuBH;
    private javax.swing.JTextField txtGhiChuPC;
    private javax.swing.JTextField txtGhiChuThuongPhat;
    private javax.swing.JTextField txtLoaiBH;
    private javax.swing.JTextField txtLoaiPhuCap;
    private javax.swing.JTextField txtLoaiThuongPhat;
    private javax.swing.JTextField txtLyDoThuongPhat;
    private javax.swing.JTextField txtNoiCapBH;
    private javax.swing.JTextField txtPCSearch;
    private javax.swing.JTextField txtSotheBH;
    private javax.swing.JTextField txtTPSearch;
    private javax.swing.JTextField txtTienPhuCap;
    private javax.swing.JTextField txtTienThuongPhat;
    // End of variables declaration//GEN-END:variables
}
