/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu.GUI;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlynhansu.Model.ChucVu;
import quanlynhansu.Model.NhanVien;
import quanlynhansu.DAO.ChucVuDAO;
import quanlynhansu.DAO.NhanVienDAO;

/**
 *
 * @author Acer
 */
public class FrmChucVu extends javax.swing.JInternalFrame {

    ArrayList<NhanVien> listnv = new ArrayList<>();
    ArrayList<ChucVu> listcv = new ArrayList<>();
    NhanVienDAO nvdao = new NhanVienDAO();
    ChucVuDAO cvdao = new ChucVuDAO();
    DefaultTableModel model;
    DefaultComboBoxModel modelManv;
    Date date, date1;

    /**
     * Creates new form FrmChucVu
     */
    public FrmChucVu() {
        initComponents();
        load();
        loadcbxMaNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMaCV = new javax.swing.JLabel();
        txtMaCV = new javax.swing.JTextField();
        txtTenCV = new javax.swing.JTextField();
        lblTenCV = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        cbxMaNV = new javax.swing.JComboBox<>();
        lblNgayBD = new javax.swing.JLabel();
        lblNgayKT = new javax.swing.JLabel();
        dateNgayBatDau = new org.jdesktop.swingx.JXDatePicker();
        datengayKetThuc = new org.jdesktop.swingx.JXDatePicker();
        lblGhiCHu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtSearchCV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChucVu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setTitle("Chức vụ");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMaCV.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMaCV.setText("Mã công việc");

        lblTenCV.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTenCV.setText("Tên công việc ");

        lblMaNhanVien.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên");

        lblNgayBD.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNgayBD.setText("Ngày bắt đầu ");

        lblNgayKT.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNgayKT.setText("Ngày kết thúc");

        lblGhiCHu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblGhiCHu.setText("Ghi chú");

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchCV.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSearchCV.setText("Tìm theo mã công việc hoặc tên cv");
        txtSearchCV.setName(""); // NOI18N
        txtSearchCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchCVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchCVMouseExited(evt);
            }
        });
        txtSearchCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCVActionPerformed(evt);
            }
        });
        txtSearchCV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCVKeyReleased(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchCV, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtSearchCV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaCV)
                            .addComponent(lblMaNhanVien))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTenCV)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGhiCHu)
                    .addComponent(lblNgayKT)
                    .addComponent(lblNgayBD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datengayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtGhiChu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxMaNV, dateNgayBatDau, datengayKetThuc, txtGhiChu, txtMaCV, txtTenCV});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayBD)
                            .addComponent(dateNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayKT)
                            .addComponent(datengayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGhiCHu)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaCV)
                            .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenCV)
                            .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNhanVien)
                            .addComponent(cbxMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxMaNV, dateNgayBatDau, datengayKetThuc, txtGhiChu, txtMaCV, txtTenCV});

        tbChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã công việc", "Tên công việc", "Mã nhân viên", "Ngày bắt đầu ", "Ngày kết thúc", "Ghi chú"
            }
        ));
        tbChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChucVu);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-add-property-30.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-edit-property-30.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-delete-30.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(215, 215, 215)
                .addComponent(btnXoa)
                .addGap(139, 139, 139))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChucVuMouseClicked
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_tbChucVuMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkform() == true) {
            insert();
            load();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (checkform() == true) {
            update();
            load();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
        load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtSearchCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchCVMouseClicked
        // TODO add your handling code here:
        txtSearchCV.setText("");
    }//GEN-LAST:event_txtSearchCVMouseClicked

    private void txtSearchCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchCVActionPerformed
        // TODO add your handling code here:
        txtSearchCV.setText(null);
    }//GEN-LAST:event_txtSearchCVActionPerformed

    private void txtSearchCVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCVKeyReleased
        // TODO add your handling code here:
        if (!txtSearchCV.getText().isEmpty()) {
            loadSearch();
        } else {
            load();
        }
    }//GEN-LAST:event_txtSearchCVKeyReleased

    private void txtSearchCVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchCVMouseExited
        // TODO add your handling code here:
        txtSearchCV.setText("Tìm theo mã công việc hoặc tên cv");
    }//GEN-LAST:event_txtSearchCVMouseExited

    private boolean checkform() {
        if (txtMaCV.getText().equals("")) {
            txtMaCV.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã công việc", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (txtTenCV.getText().equals("")) {
            txtTenCV.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên công việc", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadcbxMaNV() {
        modelManv = (DefaultComboBoxModel) cbxMaNV.getModel();
        listnv = nvdao.load();
        for (NhanVien nv : listnv) {
            modelManv.addElement(nv.getMaNhanVien());
        }
        cbxMaNV.setModel(modelManv);
    }

    private void load() {
        listcv = cvdao.load();
        model = (DefaultTableModel) tbChucVu.getModel();
        model.setRowCount(0);
        for (ChucVu cv : listcv) {
            model.addRow(new Object[]{
                cv.getMaCV(),
                cv.getTenCV(),
                cv.getMaNV(),
                cv.getNgayBatDau(),
                cv.getNgayKetThuc(),
                cv.getGhiChu(),});
        }
    }
// Hiển thị dữ liệu ra lên khi click vào table
    private void display() {
        try {
            int current = tbChucVu.getSelectedRow();
            ChucVu lg = listcv.get(current);
            txtMaCV.setText(tbChucVu.getModel().getValueAt(current, 0).toString());
            txtTenCV.setText(tbChucVu.getModel().getValueAt(current, 1).toString());
            cbxMaNV.setSelectedItem(tbChucVu.getModel().getValueAt(current, 2).toString());
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(current, 3));
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(current, 4));
            dateNgayBatDau.setDate(date);
            datengayKetThuc.setDate(date1);
            txtGhiChu.setText(tbChucVu.getModel().getValueAt(current, 5).toString());
        } catch (ParseException ex) {
            Logger.getLogger(FrmChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void insert() {
        try {
            ChucVu cv = new ChucVu();
            cv.setMaCV(txtMaCV.getText());
            cv.setTenCV(txtTenCV.getText());
            cv.setMaNV(cbxMaNV.getSelectedItem().toString());
            try {
                date = dateNgayBatDau.getDate();
                date1 = datengayKetThuc.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                cv.setNgayBatDau(df);
                cv.setNgayKetThuc(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            cv.setGhiChu(txtGhiChu.getText());
            if (cvdao.insert(cv) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm chức vụ thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã chức vụ [ " + txtMaCV.getText() + " ] đã tồn tại không thể thêm");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void update() {
        try {
            ChucVu cv = new ChucVu();
            cv.setMaCV(txtMaCV.getText());
            cv.setTenCV(txtTenCV.getText());
            cv.setMaNV(cbxMaNV.getSelectedItem().toString());
            try {
                date = dateNgayBatDau.getDate();
                date1 = datengayKetThuc.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                cv.setNgayBatDau(df);
                cv.setNgayKetThuc(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            cv.setGhiChu(txtGhiChu.getText());
            if (cvdao.update(cv) > 0) {
                JOptionPane.showMessageDialog(null, "Sửa chức vụ thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã chức vụ [ " + txtMaCV.getText() + " ]  không thể sửa");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void delete() {
        int index = tbChucVu.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1chức vụ trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");

        if (tk == JOptionPane.YES_OPTION) {

            if (cvdao.delete(txtMaCV.getText())) {
                JOptionPane.showMessageDialog(this, "Xóa chức vụ thành công", "Thông Báo", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
            }

        }
    }

    private void loadSearch() {
        listcv = cvdao.Search(txtSearchCV.getText());
        model = (DefaultTableModel) tbChucVu.getModel();
        model.setRowCount(0);
        for (ChucVu chucvu : listcv) {
            model.addRow(new Object[]{
                chucvu.getMaCV(),
                chucvu.getTenCV(),
                chucvu.getMaNV(),
                chucvu.getNgayBatDau(),
                chucvu.getNgayKetThuc(),
                chucvu.getGhiChu(),});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxMaNV;
    private org.jdesktop.swingx.JXDatePicker dateNgayBatDau;
    private org.jdesktop.swingx.JXDatePicker datengayKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGhiCHu;
    private javax.swing.JLabel lblMaCV;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayBD;
    private javax.swing.JLabel lblNgayKT;
    private javax.swing.JLabel lblTenCV;
    private javax.swing.JTable tbChucVu;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaCV;
    private javax.swing.JTextField txtSearchCV;
    private javax.swing.JTextField txtTenCV;
    // End of variables declaration//GEN-END:variables
}
