/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu.GUI;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlynhansu.Model.ChucVu;
import quanlynhansu.Model.HopDong;
import quanlynhansu.Model.PhongBan;
import quanlynhansu.DAO.ChucVuDAO;
import quanlynhansu.DAO.HopDongDAO;
import quanlynhansu.DAO.PhongBanDAO;

/**
 *
 * @author Acer
 */
public class FrmHopDong extends javax.swing.JInternalFrame {

    ArrayList<HopDong> listhd = new ArrayList<>();
    ArrayList<PhongBan> listPB = new ArrayList<>();
    ArrayList<ChucVu> listcv = new ArrayList<>();
    HopDongDAO hddao = new HopDongDAO();
    PhongBanDAO pbdao = new PhongBanDAO();
    ChucVuDAO cvdao = new ChucVuDAO();
    DefaultTableModel model;
    DefaultComboBoxModel modelMaPB, modelMaCV;
    Date date, date1;

    /**
     * Creates new form FrmHopDong
     */
    public FrmHopDong() {
        initComponents();
        load();
        loadcbxMaPB();
        loadcbxMaCV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateNgayBatDau = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        txtHSLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxPhongban = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dateNgayKetThuc = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cbxMaCV = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        txtSearchHopDong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHopDong = new javax.swing.JTable();

        setTitle("Hợp đồng");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã hợp đồng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ngày bắt đầu");

        dateNgayBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNgayBatDauActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("HS Lương");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã công việc");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã Phòng ban");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ngày kết thúc");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ghi chú");

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchHopDong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchHopDong.setText("Tìm theo mã nhân viên hoặc mã công việc");
        txtSearchHopDong.setName(""); // NOI18N
        txtSearchHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchHopDongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchHopDongMouseExited(evt);
            }
        });
        txtSearchHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchHopDongActionPerformed(evt);
            }
        });
        txtSearchHopDong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchHopDongKeyReleased(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtSearchHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHD)
                    .addComponent(cbxPhongban, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMaCV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHSLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateNgayKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxMaCV, cbxPhongban, dateNgayBatDau, dateNgayKetThuc, txtGhiChu, txtHSLuong, txtMaHD});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHSLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxMaCV, cbxPhongban, dateNgayBatDau, dateNgayKetThuc, txtGhiChu, txtHSLuong, txtMaHD});

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-add-property-30.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-edit-property-30.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-delete-30.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(246, 246, 246)
                .addComponent(btnXoa)
                .addGap(103, 103, 103))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        tbHopDong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hợp đồng", "Mã phòng ban", "Ngày bắt đầu", "Mã công viêc", "HS lương", "Ngày kết thúc", "Ghi chú"
            }
        ));
        tbHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHopDongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHopDong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHopDongMouseClicked
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_tbHopDongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkform() == true) {
            insert();
            load();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (checkform() == true) {
            update();
            load();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
        load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtSearchHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchHopDongMouseClicked
        // TODO add your handling code here:
        txtSearchHopDong.setText("");
    }//GEN-LAST:event_txtSearchHopDongMouseClicked

    private void txtSearchHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchHopDongActionPerformed
        // TODO add your handling code here:
        txtSearchHopDong.setText(null);
    }//GEN-LAST:event_txtSearchHopDongActionPerformed

    private void txtSearchHopDongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchHopDongKeyReleased
        // TODO add your handling code here:
        if (!txtSearchHopDong.getText().isEmpty()) {
            loadSearch();
        } else {
            load();
        }
    }//GEN-LAST:event_txtSearchHopDongKeyReleased

    private void txtSearchHopDongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchHopDongMouseExited
        // TODO add your handling code here:
        txtSearchHopDong.setText("Tìm theo mã nhân viên hoặc mã công việc");
    }//GEN-LAST:event_txtSearchHopDongMouseExited

    private void dateNgayBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNgayBatDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNgayBatDauActionPerformed

    private boolean checkform() {
        if (txtMaHD.getText().equals("")) {
            txtMaHD.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã hợp đồng ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!(txtHSLuong.getText().matches(".*[0-9].*"))) {
            txtHSLuong.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập số cho hệ số lương", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadcbxMaPB() {
        modelMaPB = (DefaultComboBoxModel) cbxPhongban.getModel();
        listPB = pbdao.load();
        for (PhongBan pb : listPB) {
            modelMaPB.addElement(pb.getMaPB());
        }
        cbxPhongban.setModel(modelMaPB);
    }

    private void loadcbxMaCV() {
        modelMaCV = (DefaultComboBoxModel) cbxMaCV.getModel();
        listcv = cvdao.load();
        for (ChucVu cv : listcv) {
            modelMaCV.addElement(cv.getMaCV());
        }
        cbxMaCV.setModel(modelMaCV);
    }
// Laod dữ liệu ra table
    private void load() {
        listhd = hddao.load();
        model = (DefaultTableModel) tbHopDong.getModel();
        model.setRowCount(0);
        for (HopDong pb : listhd) {
            model.addRow(new Object[]{
                pb.getMaHD(),
                pb.getPhongBan(),
                pb.getNgayBatDau(),
                pb.getMaCV(),
                pb.getHSLuong(),
                pb.getNgayKetThuc(),
                pb.getGhiChu(),});
        }
    }
// Hiển thị dữ liệu ra lên khi click vào table
    private void display() {
        try {
            int current = tbHopDong.getSelectedRow();
            HopDong lg = listhd.get(current);
            txtMaHD.setText(tbHopDong.getModel().getValueAt(current, 0).toString());
            cbxPhongban.setSelectedItem(tbHopDong.getModel().getValueAt(current, 1).toString());
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(current, 2));
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(current, 5));
            dateNgayBatDau.setDate(date);
            dateNgayKetThuc.setDate(date1);
            cbxMaCV.setSelectedItem(tbHopDong.getModel().getValueAt(current, 3).toString());
            txtHSLuong.setText(tbHopDong.getModel().getValueAt(current, 4).toString());
            txtGhiChu.setText((String) tbHopDong.getModel().getValueAt(current, 6));
        } catch (ParseException ex) {
            Logger.getLogger(FrmHopDong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void insert() {
        try {
            HopDong hd = new HopDong();
            hd.setMaHD(txtMaHD.getText());
            hd.setPhongBan(cbxPhongban.getSelectedItem().toString());
            hd.setMaCV(cbxMaCV.getSelectedItem().toString());
            try {
                date = dateNgayBatDau.getDate();
                date1 = dateNgayKetThuc.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                hd.setNgayBatDau(df);
                hd.setNgayKetThuc(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            hd.setHSLuong(Integer.parseInt(txtHSLuong.getText()));
            hd.setGhiChu(txtGhiChu.getText());
            if (hddao.insert(hd) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm  Hợp Đồng thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã hợp đồng [ " + cbxPhongban.getSelectedItem().toString() + " ] đã tồn tại không thể thêm");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void update() {
        try {
            HopDong hd = new HopDong();
            hd.setMaHD(txtMaHD.getText());
            hd.setPhongBan(cbxPhongban.getSelectedItem().toString());
            hd.setMaCV(cbxMaCV.getSelectedItem().toString());
            try {
                date = dateNgayBatDau.getDate();
                date1 = dateNgayKetThuc.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                hd.setNgayBatDau(df);
                hd.setNgayKetThuc(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            hd.setHSLuong(Integer.parseInt(txtHSLuong.getText()));
            hd.setGhiChu(txtGhiChu.getText());
            if (hddao.update(hd) > 0) {
                JOptionPane.showMessageDialog(null, "Sửa hợp đồng thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã hợp đồng [ " + txtMaHD.getText() + " ]  không thể sửa");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void delete() {
        int index = tbHopDong.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hợp đồng để xóa trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
        if (tk == JOptionPane.YES_OPTION) {
            if (hddao.delete(txtMaHD.getText())) {
                JOptionPane.showMessageDialog(this, "Xóa hợp đồng thành công", "Thông Báo", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
            }

        }
    }

    public void loadSearch() {
        listhd = hddao.Search(txtSearchHopDong.getText());
        model = (DefaultTableModel) tbHopDong.getModel();
        model.setRowCount(0);
        for (HopDong lg : listhd) {
            model.addRow(new Object[]{
                lg.getMaHD(),
                lg.getPhongBan(),
                lg.getNgayBatDau(),
                lg.getMaCV(),
                lg.getHSLuong(),
                lg.getNgayKetThuc(),
                lg.getGhiChu(),});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxMaCV;
    private javax.swing.JComboBox<String> cbxPhongban;
    private org.jdesktop.swingx.JXDatePicker dateNgayBatDau;
    private org.jdesktop.swingx.JXDatePicker dateNgayKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHopDong;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHSLuong;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtSearchHopDong;
    // End of variables declaration//GEN-END:variables
}
