/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu.GUI;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlynhansu.Model.Luong;
import quanlynhansu.Model.NhanVien;
import quanlynhansu.DAO.LuongDAO;
import quanlynhansu.DAO.NhanVienDAO;

/**
 *
 * @author Acer
 */
public class FrmLuong extends javax.swing.JInternalFrame {

    ArrayList<Luong> listlg = new ArrayList<>();
    ArrayList<NhanVien> listnv = new ArrayList<>();
    LuongDAO lgdao = new LuongDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    DefaultTableModel model;
    DefaultComboBoxModel modelManv;
    Luong lg = new Luong();
    Date date, date1;

    /**
     * Creates new form FrmLuong
     */
    public FrmLuong() {
        initComponents();
        load();
        loadcbxMaNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLuongCB = new javax.swing.JTextField();
        txtChucdanh = new javax.swing.JTextField();
        txtChucvu = new javax.swing.JTextField();
        txtPhuCapCV = new javax.swing.JTextField();
        dateNgaySua = new org.jdesktop.swingx.JXDatePicker();
        txtGhiChu = new javax.swing.JTextField();
        dateNgayNhap = new org.jdesktop.swingx.JXDatePicker();
        cbxMaNhanVien = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtSearchLuog = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLuong = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setTitle("Lương nhân viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Lương CB");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Chức danh");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("PC Chức vụ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Chức vụ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ngày nhập");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Ngày sửa");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Ghi chú");

        cbxMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchLuog.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchLuog.setText("Tìm theo mã nhân viên");
        txtSearchLuog.setName(""); // NOI18N
        txtSearchLuog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchLuogMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchLuogMouseExited(evt);
            }
        });
        txtSearchLuog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchLuogActionPerformed(evt);
            }
        });
        txtSearchLuog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchLuogKeyReleased(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchLuog, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtSearchLuog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLuongCB, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtChucdanh)
                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhuCapCV)
                    .addComponent(txtChucvu)
                    .addComponent(dateNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateNgaySua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGhiChu))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxMaNhanVien, dateNgayNhap, dateNgaySua, txtChucdanh, txtChucvu, txtGhiChu, txtLuongCB, txtPhuCapCV});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgaySua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhuCapCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtChucdanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(dateNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxMaNhanVien, dateNgayNhap, dateNgaySua, txtChucdanh, txtChucvu, txtGhiChu, txtLuongCB, txtPhuCapCV});

        tbLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Lương CB", "Chức danh", "Chức vụ", "PC Chức vụ", "Ngày nhập", "Ngày sửa", "Ghi chú"
            }
        ));
        tbLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLuong);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-add-property-30.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-edit-property-30.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-delete-30.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(286, 286, 286)
                .addComponent(btnXoa)
                .addGap(104, 104, 104))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSua, btnThem, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLuongMouseClicked
        // TODO add your handling code here:
        display();

    }//GEN-LAST:event_tbLuongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkform() == true) {
            insert();
            load();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
        load();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (checkform() == true) {
            delete();
            load();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtSearchLuogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchLuogMouseClicked
        // TODO add your handling code here:
        txtSearchLuog.setText("");
    }//GEN-LAST:event_txtSearchLuogMouseClicked

    private void txtSearchLuogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLuogActionPerformed
        // TODO add your handling code here:
        txtSearchLuog.setText(null);
    }//GEN-LAST:event_txtSearchLuogActionPerformed

    private void txtSearchLuogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchLuogKeyReleased
        // TODO add your handling code here:
        if (!txtSearchLuog.getText().isEmpty()) {
            loadSearch();
        } else {
            load();
        }
    }//GEN-LAST:event_txtSearchLuogKeyReleased

    private void txtSearchLuogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchLuogMouseExited
        // TODO add your handling code here:
        txtSearchLuog.setText("Tìm theo mã nhân viên");
    }//GEN-LAST:event_txtSearchLuogMouseExited
    private boolean checkform() {
        if (!(txtLuongCB.getText().matches(".*[0-9].*"))) //Sử dụng biểu thức chính quy cho phép lương chỉ nhập số 
        {
            txtLuongCB.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập số cho lương ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (txtChucdanh.getText().equals("")) {
            txtChucdanh.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập chức danh", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (txtChucvu.getText().equals("")) {
            txtChucvu.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập chức vụ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!(txtPhuCapCV.getText().matches(".*[0-9].*"))) // đoạn này em sử dụng biểu thức chính quy của java để kiểm tra nhập vào luôn là số
        {
            txtPhuCapCV.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập số cho phụ cấp chức vụ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (txtGhiChu.getText().equals("")) {
            txtGhiChu.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập HS lương", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadcbxMaNV() {
        modelManv = (DefaultComboBoxModel) cbxMaNhanVien.getModel();
        listnv = nvdao.load();
        for (NhanVien nv : listnv) {
            modelManv.addElement(nv.getMaNhanVien());
        }
        cbxMaNhanVien.setModel(modelManv);
    }

    private void load() {
        listlg = lgdao.load();
        model = (DefaultTableModel) tbLuong.getModel();
        model.setRowCount(0);
        for (Luong lg : listlg) {
            model.addRow(new Object[]{
                lg.getMaNV(),
                lg.getLuongCB(),
                lg.getChucDanh(),
                lg.getChucVu(),
                lg.getPCChucVu(),
                lg.getNgayNhap(),
                lg.getNgaySua(),
                lg.getGhiChu()
            });
        }
    }
// Hiển thị dữ liệu ra lên khi click vào table
    public void display() {
        int current = tbLuong.getSelectedRow();
        lg = listlg.get(current);
        cbxMaNhanVien.setSelectedItem(tbLuong.getModel().getValueAt(current, 0).toString());
        txtLuongCB.setText(tbLuong.getModel().getValueAt(current, 1).toString());
        txtChucdanh.setText(tbLuong.getModel().getValueAt(current, 2).toString());
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(current, 5));
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(current, 6));
            dateNgayNhap.setDate(date);
            dateNgaySua.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(FrmthongtinNV.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtChucvu.setText(tbLuong.getModel().getValueAt(current, 3).toString());
        txtPhuCapCV.setText(tbLuong.getModel().getValueAt(current, 4).toString());
        txtGhiChu.setText(tbLuong.getModel().getValueAt(current, 7).toString());

    }

    public void insert() {
        try {
            lg.setMaNV(cbxMaNhanVien.getSelectedItem().toString());
            lg.setLuongCB(Integer.parseInt(txtLuongCB.getText()));
            lg.setChucDanh(txtChucdanh.getText());
            lg.setChucVu(txtChucvu.getText());
            try {
                date = dateNgayNhap.getDate();
                date1 = dateNgaySua.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                lg.setNgayNhap(df);
                lg.setNgaySua(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            lg.setPCChucVu(Integer.parseInt(txtPhuCapCV.getText()));
            lg.setGhiChu(txtGhiChu.getText());
            if (lgdao.insert(lg) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNhanVien.getSelectedItem().toString() + " ] đã tồn tại không thể thêm");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    public void update() {
        try {
            lg.setMaNV(cbxMaNhanVien.getSelectedItem().toString());
            lg.setLuongCB(Integer.parseInt(txtLuongCB.getText()));
            lg.setChucDanh(txtChucdanh.getText());
            lg.setChucVu(txtChucvu.getText());
            try {
                date = dateNgayNhap.getDate();
                date1 = dateNgaySua.getDate();
                String df = new SimpleDateFormat("yyyy-MM-dd").format(date);
                String df1 = new SimpleDateFormat("yyyy-MM-dd").format(date1);
                lg.setNgayNhap(df);
                lg.setNgaySua(df1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            lg.setPCChucVu(Integer.parseInt(txtPhuCapCV.getText()));
            lg.setGhiChu(txtGhiChu.getText());
            if (lgdao.update(lg) > 0) {
                JOptionPane.showMessageDialog(null, "Sửa  lương thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Mã nhân viên [ " + cbxMaNhanVien.getSelectedItem().toString() + " ]  không thể sửa");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    public void delete() {
        int index = tbLuong.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 Lương trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
        if (tk == JOptionPane.YES_OPTION) {
            if (lgdao.delete(cbxMaNhanVien.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Xóa Lương thành công", "Thông Báo", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
            }

        }
    }

    public void loadSearch() {
        listlg = lgdao.Search(txtSearchLuog.getText());
        model = (DefaultTableModel) tbLuong.getModel();
        model.setRowCount(0);
        for (Luong lg : listlg) {
            model.addRow(new Object[]{
                lg.getMaNV(),
                lg.getLuongCB(),
                lg.getChucDanh(),
                lg.getChucVu(),
                lg.getPCChucVu(),
                lg.getNgayNhap(),
                lg.getNgaySua(),
                lg.getGhiChu(),});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxMaNhanVien;
    private org.jdesktop.swingx.JXDatePicker dateNgayNhap;
    private org.jdesktop.swingx.JXDatePicker dateNgaySua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLuong;
    private javax.swing.JTextField txtChucdanh;
    private javax.swing.JTextField txtChucvu;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtLuongCB;
    private javax.swing.JTextField txtPhuCapCV;
    private javax.swing.JTextField txtSearchLuog;
    // End of variables declaration//GEN-END:variables
}
