/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu.GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import quanlynhansu.GUI.FrmthongtinNV;
import quanlynhansu.Model.TaiKhoan;

/**
 *
 * @author Acer
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        btnNhanSuActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnNhanSu = new javax.swing.JButton();
        btnTienLuong = new javax.swing.JButton();
        btnCheDo = new javax.swing.JButton();
        btnChucVu = new javax.swing.JButton();
        btnBangChamCong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desktopmain = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        btnHopdong = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnPhongban = new javax.swing.JButton();
        lblQuyen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnDoiMK = new javax.swing.JMenuItem();
        MnTaoTaiKhoan = new javax.swing.JMenuItem();
        MnDangXuat = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MnNhanSu = new javax.swing.JMenuItem();
        MnPhongban = new javax.swing.JMenuItem();
        MnTienLuong = new javax.swing.JMenuItem();
        MnChamCong = new javax.swing.JMenuItem();
        jMenuNhansu = new javax.swing.JMenu();
        MnChucVu = new javax.swing.JMenuItem();
        MnHopDong = new javax.swing.JMenuItem();
        MnCheDo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân sự -Lê Thành Công");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("QLNS"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        btnNhanSu.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnNhanSu.setText("Nhân Sự");
        btnNhanSu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanSuActionPerformed(evt);
            }
        });

        btnTienLuong.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnTienLuong.setText("Tiền Lương");
        btnTienLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTienLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienLuongActionPerformed(evt);
            }
        });

        btnCheDo.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnCheDo.setText("Chế Độ ");
        btnCheDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheDoActionPerformed(evt);
            }
        });

        btnChucVu.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btnChucVu.setText("Chức vụ");
        btnChucVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChucVuActionPerformed(evt);
            }
        });

        btnBangChamCong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBangChamCong.setText("Bảng chấm công");
        btnBangChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangChamCongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(btnNhanSu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnTienLuong)
                .addGap(80, 80, 80)
                .addComponent(btnCheDo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnBangChamCong)
                .addGap(109, 109, 109))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCheDo, btnChucVu});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBangChamCong)
                    .addComponent(btnChucVu)
                    .addComponent(btnCheDo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTienLuong)
                    .addComponent(btnNhanSu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBangChamCong, btnCheDo, btnChucVu, btnNhanSu, btnTienLuong});

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("QUẢN LÝ NHÂN SỰ");

        desktopmain.setAutoscrolls(true);
        desktopmain.setDesktopManager(null);
        desktopmain.setDoubleBuffered(true);

        javax.swing.GroupLayout desktopmainLayout = new javax.swing.GroupLayout(desktopmain);
        desktopmain.setLayout(desktopmainLayout);
        desktopmainLayout.setHorizontalGroup(
            desktopmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        desktopmainLayout.setVerticalGroup(
            desktopmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        btnHopdong.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        btnHopdong.setText("Hợp Đồng");
        btnHopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopdongActionPerformed(evt);
            }
        });

        btnThongke.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnThongke.setText("Thống kê");
        btnThongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });

        btnPhongban.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        btnPhongban.setText("Phòng\n Ban");
        btnPhongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongbanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhongban)
                    .addComponent(btnHopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongke))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHopdong, btnPhongban, btnThongke});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnHopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        lblQuyen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuyen.setForeground(new java.awt.Color(255, 0, 51));
        lblQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-key-24.png"))); // NOI18N
        lblQuyen.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333)
                .addComponent(lblQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktopmain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(150, 32769));

        jMenu1.setText("Tài khoản");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        MnDoiMK.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnDoiMK.setText("Đổi mật khẩu");
        MnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDoiMKActionPerformed(evt);
            }
        });
        jMenu1.add(MnDoiMK);

        MnTaoTaiKhoan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnTaoTaiKhoan.setText("Tạo tài khoản");
        MnTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTaoTaiKhoanActionPerformed(evt);
            }
        });
        jMenu1.add(MnTaoTaiKhoan);

        MnDangXuat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnDangXuat.setText("Đăng xuất");
        MnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(MnDangXuat);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Quản Lý");
        jMenu4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        MnNhanSu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnNhanSu.setText("Nhân sự");
        MnNhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNhanSuActionPerformed(evt);
            }
        });
        jMenu4.add(MnNhanSu);

        MnPhongban.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnPhongban.setText("Phòng ban");
        MnPhongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPhongbanActionPerformed(evt);
            }
        });
        jMenu4.add(MnPhongban);

        MnTienLuong.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnTienLuong.setText("Tiền lương");
        MnTienLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTienLuongActionPerformed(evt);
            }
        });
        jMenu4.add(MnTienLuong);

        MnChamCong.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnChamCong.setText("Bảng chấm công");
        MnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnChamCongActionPerformed(evt);
            }
        });
        jMenu4.add(MnChamCong);

        jMenuBar1.add(jMenu4);

        jMenuNhansu.setText("Danh mục");
        jMenuNhansu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        MnChucVu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnChucVu.setText("Chức vụ");
        MnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnChucVuActionPerformed(evt);
            }
        });
        jMenuNhansu.add(MnChucVu);

        MnHopDong.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnHopDong.setText("Hợp đồng");
        MnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHopDongActionPerformed(evt);
            }
        });
        jMenuNhansu.add(MnHopDong);

        MnCheDo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MnCheDo.setText("Chế độ");
        MnCheDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCheDoActionPerformed(evt);
            }
        });
        jMenuNhansu.add(MnCheDo);

        jMenuBar1.add(jMenuNhansu);

        jMenu5.setText("Chức năng");
        jMenu5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem14.setText("Thống kê");
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1311, 786));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void MnNhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNhanSuActionPerformed
        try {
            // TODO add your handling code here:
            FrmthongtinNV nv = new FrmthongtinNV();

            desktopmain.removeAll();
            desktopmain.add(nv).setVisible(true);

            nv.setMaximum(true);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnNhanSuActionPerformed

    private void MnPhongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPhongbanActionPerformed
        try {
            // TODO add your handling code here:
            FrmPhongban pbFrmPhongban = new FrmPhongban();
            desktopmain.removeAll();
            desktopmain.add(pbFrmPhongban).setVisible(true);
            pbFrmPhongban.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnPhongbanActionPerformed

    private void MnTienLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTienLuongActionPerformed
        try {
            // TODO add your handling code here:
            FrmLuong luong = new FrmLuong();
            desktopmain.removeAll();
            desktopmain.add(luong).setVisible(true);
            luong.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnTienLuongActionPerformed

    private void btnNhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanSuActionPerformed
        try {
            // TODO add your handling code here:
            FrmthongtinNV nv = new FrmthongtinNV();
            desktopmain.removeAll();
            desktopmain.add(nv).setVisible(true);
            nv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNhanSuActionPerformed

    private void MnCheDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCheDoActionPerformed
        // TODO add your handling code here:
        FrmCheDo cdCheDo = new FrmCheDo();
        desktopmain.removeAll();
        desktopmain.add(cdCheDo).setVisible(true);
        try {
            cdCheDo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnCheDoActionPerformed

    private void MnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnChamCongActionPerformed
        // TODO add your handling code here:
        FrmChamCong chamCong = new FrmChamCong();
        desktopmain.removeAll();
        desktopmain.add(chamCong).setVisible(true);
        try {
            chamCong.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnChamCongActionPerformed

    private void MnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHopDongActionPerformed
        // TODO add your handling code here:
        FrmHopDong hopDong = new FrmHopDong();
        desktopmain.removeAll();
        desktopmain.add(hopDong).setVisible(true);
        try {
            hopDong.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnHopDongActionPerformed

    private void MnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnChucVuActionPerformed
        // TODO add your handling code here:
        FrmChucVu ChucVu = new FrmChucVu();
        desktopmain.removeAll();
        desktopmain.add(ChucVu).setVisible(true);
        try {
            ChucVu.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnChucVuActionPerformed

    private void btnTienLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienLuongActionPerformed
        // TODO add your handling code here:
        try {
            FrmLuong luong = new FrmLuong();
            desktopmain.removeAll();
            desktopmain.add(luong).setVisible(true);
            luong.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTienLuongActionPerformed

    private void MnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDoiMKActionPerformed
        // TODO add your handling code here:

        FrmDoiMatKhau DoiMatKhau = new FrmDoiMatKhau();
        DoiMatKhau.setVisible(true);

    }//GEN-LAST:event_MnDoiMKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int hoi = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình không?", null, JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            setDefaultCloseOperation(FrmMain.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:

        try {
            FrmThongKe tk = new FrmThongKe();
            desktopmain.removeAll();
            desktopmain.add(tk).setVisible(true);
            tk.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void MnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDangXuatActionPerformed
        // TODO add your handling code here:

        int hoi = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không?", null, JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            dispose();
            FrmDangNhap dn = new FrmDangNhap();
            dn.setVisible(true);
        } else {
            setDefaultCloseOperation(FrmMain.DO_NOTHING_ON_CLOSE);
        }

    }//GEN-LAST:event_MnDangXuatActionPerformed

    private void btnCheDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheDoActionPerformed
        // TODO add your handling code here:
        try {
            FrmCheDo cd = new FrmCheDo();
            desktopmain.removeAll();
            desktopmain.add(cd).setVisible(true);
            cd.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheDoActionPerformed

    private void btnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucVuActionPerformed
        // TODO add your handling code here:
        try {
            FrmChucVu cv = new FrmChucVu();
            desktopmain.removeAll();
            desktopmain.add(cv).setVisible(true);
            cv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChucVuActionPerformed

    private void btnBangChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangChamCongActionPerformed
        // TODO add your handling code here:
        try {
            FrmChamCong chamcong = new FrmChamCong();
            desktopmain.removeAll();
            desktopmain.add(chamcong).setVisible(true);
            chamcong.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBangChamCongActionPerformed

    private void btnPhongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongbanActionPerformed
        // TODO add your handling code here:
        try {
            FrmPhongban pb = new FrmPhongban();
            desktopmain.removeAll();
            desktopmain.add(pb).setVisible(true);
            pb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPhongbanActionPerformed

    private void btnHopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopdongActionPerformed
        // TODO add your handling code here:
        try {
            FrmHopDong hd = new FrmHopDong();
            desktopmain.removeAll();
            desktopmain.add(hd).setVisible(true);
            hd.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHopdongActionPerformed

    private void MnTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTaoTaiKhoanActionPerformed
        // TODO add your handling code here:
         FrmTaoTaiKhoan taoTaiKhoan = new FrmTaoTaiKhoan();
        taoTaiKhoan.setVisible(true);
    }//GEN-LAST:event_MnTaoTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnChamCong;
    private javax.swing.JMenuItem MnCheDo;
    private javax.swing.JMenuItem MnChucVu;
    private javax.swing.JMenuItem MnDangXuat;
    private javax.swing.JMenuItem MnDoiMK;
    private javax.swing.JMenuItem MnHopDong;
    private javax.swing.JMenuItem MnNhanSu;
    private javax.swing.JMenuItem MnPhongban;
    private javax.swing.JMenuItem MnTaoTaiKhoan;
    private javax.swing.JMenuItem MnTienLuong;
    private javax.swing.JButton btnBangChamCong;
    private javax.swing.JButton btnCheDo;
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnHopdong;
    private javax.swing.JButton btnNhanSu;
    private javax.swing.JButton btnPhongban;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnTienLuong;
    private javax.swing.JDesktopPane desktopmain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenu jMenuNhansu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblQuyen;
    // End of variables declaration//GEN-END:variables
}
