/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu.GUI;

import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import quanlynhansu.DAO.BaoHiemDAO;
import quanlynhansu.DAO.ChamCongDAO;
import quanlynhansu.DAO.ChucVuDAO;
import quanlynhansu.DAO.HopDongDAO;
import quanlynhansu.DAO.LuongDAO;
import quanlynhansu.DAO.NhanVienDAO;
import quanlynhansu.DAO.PhongBanDAO;
import quanlynhansu.DAO.PhuCapDAO;
import quanlynhansu.DAO.ThongKeDAO;
import quanlynhansu.DAO.ThuongPhatDAO;
import quanlynhansu.Model.BaoHiem;
import quanlynhansu.Model.ChamCong;
import quanlynhansu.Model.ChucVu;
import quanlynhansu.Model.HopDong;
import quanlynhansu.Model.Luong;
import quanlynhansu.Model.NhanVien;
import quanlynhansu.Model.PhongBan;
import quanlynhansu.Model.PhuCap;
import quanlynhansu.Model.ThuongPhat;

/**
 *
 * @author Acer
 */
public class NhanVienUser extends javax.swing.JFrame {

    ArrayList<NhanVien> listnv = new ArrayList<>();

    NhanVienDAO nvdao = new NhanVienDAO();
    NhanVien nv = new NhanVien();
    DefaultTableModel model;
    DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();


    ArrayList<PhongBan> listpb = new ArrayList<>();
    PhongBanDAO pbdao = new PhongBanDAO();
    DefaultTableModel modelPb;
    PhongBan pb = new PhongBan();

    ArrayList<Luong> listlg = new ArrayList<>();
    Luong lg = new Luong();
    LuongDAO lgdao = new LuongDAO();

    ArrayList<HopDong> listhd = new ArrayList<>();
    ArrayList<PhongBan> listPB = new ArrayList<>();
    ArrayList<ChucVu> listcv = new ArrayList<>();
    HopDongDAO hddao = new HopDongDAO();

    ChucVuDAO cvdao = new ChucVuDAO();

    ArrayList<BaoHiem> listbh = new ArrayList<>();
    ArrayList<PhuCap> listpc = new ArrayList<>();
    ArrayList<ThuongPhat> listtp = new ArrayList<>();

    BaoHiemDAO bhdao = new BaoHiemDAO();
    PhuCapDAO pcdao = new PhuCapDAO();
    ThuongPhatDAO tpdao = new ThuongPhatDAO();

    
     ArrayList<ChamCong> listchamcog = new ArrayList<>();
    ChamCongDAO chamCongdao = new ChamCongDAO();
    
      ThongKeDAO tkdao = new ThongKeDAO();

    /**
     * Creates new form NhanVienUser
     */
    public NhanVienUser() {
        initComponents();
       loaddata();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        test = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtSearchPhongBan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhongBan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtSearchLuog = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLuong = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHopDong = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        txtSearchHopDong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbChucVu = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        txtSearchCV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbBaohiem = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        txtBHSearch = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txtPCSearch = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbPhuCap = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbChamCong = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        txtSearchchamcong = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbThuongPhat = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        txtTPSearch = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbNhanvien = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txtSearchNhanSu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuyen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MNDoiMK = new javax.swing.JMenuItem();
        MnDangXuat = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        test.setVisible(true);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testLayout = new javax.swing.GroupLayout(test.getContentPane());
        test.getContentPane().setLayout(testLayout);
        testLayout.setHorizontalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButton1)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        testLayout.setVerticalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton1)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(test)
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(test)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel12.setBackground(new java.awt.Color(0, 102, 204));
        jPanel12.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchPhongBan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchPhongBan.setText("Tìm kiếm theo mã phòng hoặc tên phòng");
        txtSearchPhongBan.setName(""); // NOI18N
        txtSearchPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchPhongBanMouseClicked(evt);
            }
        });
        txtSearchPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchPhongBanActionPerformed(evt);
            }
        });
        txtSearchPhongBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchPhongBanKeyReleased(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(txtSearchPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbPhongBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã PB", "Tên PB", "Tên BP", "Ngày thành lập", "PC Chức vụ", "Số lượng", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(tbPhongBan);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Thông tin phòng ban");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(516, 516, 516)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(454, 454, 454)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Phòng ban", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jPanel13.setBackground(new java.awt.Color(0, 102, 204));
        jPanel13.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchLuog.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchLuog.setText("Tìm theo mã nhân viên or tên nhân viên");
        txtSearchLuog.setName(""); // NOI18N
        txtSearchLuog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchLuogMouseClicked(evt);
            }
        });
        txtSearchLuog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchLuogActionPerformed(evt);
            }
        });
        txtSearchLuog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchLuogKeyReleased(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchLuog, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(txtSearchLuog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Lương CB", "HS Lương ", "Giới tính", "Phụ cấp", "Số ngày công", "Số giờ tăng ca", "Lương Thực lãnh"
            }
        ));
        jScrollPane2.setViewportView(tbLuong);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Thông tin Lương");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Lương", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        tbHopDong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hợp đồng", "Mã phòng ban", "Ngày bắt đầu", "Mã công viêc", "HS lương", "Ngày kết thúc", "Ghi chú"
            }
        ));
        jScrollPane4.setViewportView(tbHopDong);

        jPanel14.setBackground(new java.awt.Color(0, 102, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchHopDong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchHopDong.setText("Tìm theo mã nhân viên hoặc mã công việc");
        txtSearchHopDong.setName(""); // NOI18N
        txtSearchHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchHopDongMouseClicked(evt);
            }
        });
        txtSearchHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchHopDongActionPerformed(evt);
            }
        });
        txtSearchHopDong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchHopDongKeyReleased(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtSearchHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Thông tin hợp đồng");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(516, 516, 516)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(436, 436, 436)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 484, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Hợp đồng", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));

        tbChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã công việc", "Tên công việc", "Mã nhân viên", "Ngày bắt đầu ", "Ngày kết thúc", "Ghi chú"
            }
        ));
        jScrollPane5.setViewportView(tbChucVu);

        jPanel15.setBackground(new java.awt.Color(0, 102, 204));
        jPanel15.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchCV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchCV.setText("Tìm theo mã công việc hoặc tên cv");
        txtSearchCV.setName(""); // NOI18N
        txtSearchCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchCVMouseClicked(evt);
            }
        });
        txtSearchCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCVActionPerformed(evt);
            }
        });
        txtSearchCV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCVKeyReleased(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchCV, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(txtSearchCV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Thông tin chức vụ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(514, 514, 514))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Chức vụ", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        tbBaohiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbBaohiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Loại bảo hiểm", "Số thẻ BH", "Ngày cấp", "Ngày hết hạn", "Nơi cấp", "Ghichu"
            }
        ));
        tbBaohiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBaohiemMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbBaohiem);

        jPanel16.setBackground(new java.awt.Color(0, 102, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtBHSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBHSearch.setText("Tìm theo mã nhân viên or số thẻ BH");
        txtBHSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBHSearchMouseClicked(evt);
            }
        });
        txtBHSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBHSearchActionPerformed(evt);
            }
        });
        txtBHSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBHSearchKeyReleased(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBHSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(txtBHSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Thông tin bảo hiểm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(521, 521, 521)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bảo hiểm", jPanel6);

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));

        jPanel17.setBackground(new java.awt.Color(0, 102, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtPCSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPCSearch.setText("Tìm theo mã nhân viên ");
        txtPCSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPCSearchMouseClicked(evt);
            }
        });
        txtPCSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPCSearchActionPerformed(evt);
            }
        });
        txtPCSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPCSearchKeyReleased(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPCSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(txtPCSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbPhuCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Loại phụ cấp", "Tiền phụ cấp", "Từ ngày", "Đến ngày", "Ghi chú"
            }
        ));
        jScrollPane7.setViewportView(tbPhuCap);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Thông tin phụ cấp");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(521, 521, 521)
                                .addComponent(jLabel5))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 469, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Phụ cấp ", jPanel9);

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        tbChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Ngày", "Tình trạng", "Phụ cấp chức vụ", "Phụ cấp khác", "Số ngày công", "Số ngày nghỉ", "Số giờ tăng ca", "Ghi chú"
            }
        ));
        jScrollPane9.setViewportView(tbChamCong);

        jPanel19.setBackground(new java.awt.Color(0, 102, 204));
        jPanel19.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchchamcong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchchamcong.setText("Tìm kiếm theo mã nhân viên");
        txtSearchchamcong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchchamcongMouseClicked(evt);
            }
        });
        txtSearchchamcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchchamcongActionPerformed(evt);
            }
        });
        txtSearchchamcong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchchamcongKeyReleased(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchchamcong, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(txtSearchchamcong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Thông tin bảng chấm công");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(482, 482, 482)
                                .addComponent(jLabel4))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(427, 427, 427)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 474, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chấm công", jPanel11);

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        tbThuongPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Loại", "Tiền", "Lý do", "Ngày", "Ghi chú"
            }
        ));
        jScrollPane8.setViewportView(tbThuongPhat);

        jPanel18.setBackground(new java.awt.Color(0, 102, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtTPSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTPSearch.setText("Tìm theo mã nhân viên or loại");
        txtTPSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTPSearchMouseClicked(evt);
            }
        });
        txtTPSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPSearchActionPerformed(evt);
            }
        });
        txtTPSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTPSearchKeyReleased(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTPSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(txtTPSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Thông tin thưởng phạt");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(503, 503, 503))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thưởng phạt", jPanel10);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tbNhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tbNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Mã phòng ban", "Mã hợp đồng", "HS Lương", "Họ tên", "Giới tính", "Ngày sinh", "CMND", "SDT", "Trình độ HV", "Địa chỉ", "Email", "TT hôn nhân"
            }
        ));
        jScrollPane3.setViewportView(tbNhanvien);

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));
        jPanel7.setToolTipText("Tiềm kiếm theo mã nhân  hoặc tên");

        txtSearchNhanSu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchNhanSu.setText("Tìm kiếm theo mã nhân viên hoặc tên");
        txtSearchNhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchNhanSuMouseClicked(evt);
            }
        });
        txtSearchNhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNhanSuActionPerformed(evt);
            }
        });
        txtSearchNhanSu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNhanSuKeyReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-search-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchNhanSu, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtSearchNhanSu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Thông tin nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(534, 534, 534))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhân viên", jPanel1);

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("QUẢN LÝ NHÂN SỰ");

        txtQuyen.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtQuyen.setForeground(new java.awt.Color(255, 0, 51));
        txtQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlynhansu/Icon/icons8-key-24.png"))); // NOI18N
        txtQuyen.setText("Nhân viên");

        jMenu2.setText("Tài khoản ");
        jMenu2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        MNDoiMK.setText("Đổi mật khẩu");
        MNDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNDoiMKActionPerformed(evt);
            }
        });
        jMenu2.add(MNDoiMK);

        MnDangXuat.setText("Đăng xuất");
        MnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDangXuatActionPerformed(evt);
            }
        });
        jMenu2.add(MnDangXuat);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(352, 352, 352)
                .addComponent(txtQuyen)
                .addGap(59, 59, 59))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loaddata()
    {
     loadNS();
        loadPB();
        loadLuong();
        loadHD();
        loadCV();
        loadBH();
        loadPC();
        loadTP();
        loadChamCong();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchNhanSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchNhanSuMouseClicked
        // TODO add your handling code here:
        txtSearchNhanSu.setText("");
    }//GEN-LAST:event_txtSearchNhanSuMouseClicked

    private void txtSearchNhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNhanSuActionPerformed
        // TODO add your handling code here:
        //        txtSearch.setText(null);
    }//GEN-LAST:event_txtSearchNhanSuActionPerformed

    private void txtSearchNhanSuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNhanSuKeyReleased
        // TODO add your handling code here:
        if (!txtSearchNhanSu.getText().isEmpty()) {
            loadSearchNS();
        } else {
            loadNS();
        }
    }//GEN-LAST:event_txtSearchNhanSuKeyReleased

    private void txtSearchPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchPhongBanMouseClicked
        // TODO add your handling code here:
        txtSearchPhongBan.setText("");
    }//GEN-LAST:event_txtSearchPhongBanMouseClicked

    private void txtSearchPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPhongBanActionPerformed
        // TODO add your handling code here:
        txtSearchPhongBan.setText(null);
    }//GEN-LAST:event_txtSearchPhongBanActionPerformed

    private void txtSearchPhongBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPhongBanKeyReleased
        // TODO add your handling code here:
        if (!txtSearchNhanSu.getText().isEmpty()) {
            loadSearchPB();
        } else {
            loadPB();
        }
    }//GEN-LAST:event_txtSearchPhongBanKeyReleased

    private void txtSearchLuogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchLuogMouseClicked
        // TODO add your handling code here:
        txtSearchLuog.setText("");
    }//GEN-LAST:event_txtSearchLuogMouseClicked

    private void txtSearchLuogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLuogActionPerformed
        // TODO add your handling code here:
        txtSearchLuog.setText(null);
    }//GEN-LAST:event_txtSearchLuogActionPerformed

    private void txtSearchLuogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchLuogKeyReleased
        // TODO add your handling code here:
        if (!txtSearchLuog.getText().isEmpty()) {
            loadSearchLuong();
        } else {
            loadLuong();
        }
    }//GEN-LAST:event_txtSearchLuogKeyReleased

    private void txtSearchHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchHopDongMouseClicked
        // TODO add your handling code here:
        txtSearchHopDong.setText("");
    }//GEN-LAST:event_txtSearchHopDongMouseClicked

    private void txtSearchHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchHopDongActionPerformed
        // TODO add your handling code here:
        txtSearchHopDong.setText(null);
    }//GEN-LAST:event_txtSearchHopDongActionPerformed

    private void txtSearchHopDongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchHopDongKeyReleased
        // TODO add your handling code here:
        if (!txtSearchHopDong.getText().isEmpty()) {
            loadSearchHD();
        } else {
            loadHD();
        }
    }//GEN-LAST:event_txtSearchHopDongKeyReleased

    private void txtSearchCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchCVMouseClicked
        // TODO add your handling code here:
        txtSearchCV.setText("");
    }//GEN-LAST:event_txtSearchCVMouseClicked

    private void txtSearchCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchCVActionPerformed
        // TODO add your handling code here:
        txtSearchCV.setText(null);
    }//GEN-LAST:event_txtSearchCVActionPerformed

    private void txtSearchCVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCVKeyReleased
        // TODO add your handling code here:
        if (!txtSearchCV.getText().isEmpty()) {
            loadSearchCV();
        } else {
            loadCV();
        }
    }//GEN-LAST:event_txtSearchCVKeyReleased

    private void tbBaohiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBaohiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBaohiemMouseClicked

    private void txtBHSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBHSearchMouseClicked
        // TODO add your handling code here:
        txtBHSearch.setText("");
    }//GEN-LAST:event_txtBHSearchMouseClicked

    private void txtBHSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBHSearchActionPerformed
        // TODO add your handling code here:
        txtBHSearch.setText(null);
    }//GEN-LAST:event_txtBHSearchActionPerformed

    private void txtBHSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBHSearchKeyReleased
        if (!txtBHSearch.getText().isEmpty()) {
            loadSearchBH();
        } else {
            loadBH();
        }
    }//GEN-LAST:event_txtBHSearchKeyReleased

    private void txtPCSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPCSearchMouseClicked
        // TODO add your handling code here:
        txtPCSearch.setText("");
    }//GEN-LAST:event_txtPCSearchMouseClicked

    private void txtPCSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPCSearchActionPerformed
        // TODO add your handling code here:
        txtPCSearch.setText(null);
    }//GEN-LAST:event_txtPCSearchActionPerformed

    private void txtPCSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCSearchKeyReleased
        // TODO add your handling code here:
        if (!txtPCSearch.getText().isEmpty()) {
            loadSearchPC();
        } else {
            loadPC();
        }
    }//GEN-LAST:event_txtPCSearchKeyReleased

    private void txtTPSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTPSearchMouseClicked
        // TODO add your handling code here:
        txtTPSearch.setText(null);
    }//GEN-LAST:event_txtTPSearchMouseClicked

    private void txtTPSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPSearchActionPerformed
        // TODO add your handling code here:
        txtTPSearch.setText(null);
    }//GEN-LAST:event_txtTPSearchActionPerformed

    private void txtTPSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTPSearchKeyReleased
        // TODO add your handling code here:
        if (!txtTPSearch.getText().isEmpty()) {
            loadSearchTP();
        } else {
            loadTP();
        }
    }//GEN-LAST:event_txtTPSearchKeyReleased

    private void txtSearchchamcongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchchamcongMouseClicked
        // TODO add your handling code here:
        txtSearchchamcong.setText("");

    }//GEN-LAST:event_txtSearchchamcongMouseClicked

    private void txtSearchchamcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchchamcongActionPerformed
        // TODO add your handling code here:
        txtSearchchamcong.setText(null);
    }//GEN-LAST:event_txtSearchchamcongActionPerformed

    private void txtSearchchamcongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchchamcongKeyReleased
        if (!txtSearchchamcong.getText().isEmpty()) {
            loadSearchChamCong();
        } else {
            loadChamCong();
        }
    }//GEN-LAST:event_txtSearchchamcongKeyReleased

    private void MNDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNDoiMKActionPerformed
        // TODO add your handling code here:
           FrmDoiMatKhau DoiMatKhau = new FrmDoiMatKhau();
        DoiMatKhau.setVisible(true);
    }//GEN-LAST:event_MNDoiMKActionPerformed

    private void MnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDangXuatActionPerformed
        // TODO add your handling code here:
        Dangxuat();
    }//GEN-LAST:event_MnDangXuatActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int hoi = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            dispose();
            FrmDangNhap dn = new FrmDangNhap();
            dn.setVisible(true);
        } else {
            setDefaultCloseOperation(NhanVienUser.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private  void Dangxuat()
    {
         int hoi = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            dispose();
            FrmDangNhap dn = new FrmDangNhap();
            dn.setVisible(true);
        } else {
            setDefaultCloseOperation(NhanVienUser.DO_NOTHING_ON_CLOSE);
        }
    }
    
    private void loadNS() {
        listnv = nvdao.load();
        model = (DefaultTableModel) tbNhanvien.getModel();
        model.setRowCount(0);
        for (NhanVien nv : listnv) {
            model.addRow(new Object[]{
                nv.getMaNhanVien(),
                nv.getMaPB(),
                nv.getMaHD(),
                nv.getHeSoLuong(),
                nv.getTenNV(),
                nv.getGioiTinh(),
                nv.getNgaySinh(),
                nv.getSoCM(),
                nv.getDienThoai(),
                nv.getTrinhDoHV(),
                nv.getDiaChi(),
                nv.getEmail(),
                nv.getTTHonNhan()
            });
        }
    }

    public void loadSearchNS() {
        listnv = nvdao.SearchTen(txtSearchNhanSu.getText());
        model = (DefaultTableModel) tbNhanvien.getModel();
        model.setRowCount(0);
        for (NhanVien nv : listnv) {
            model.addRow(new Object[]{
                nv.getMaNhanVien(),
                nv.getMaPB(),
                nv.getMaHD(),
                nv.getHeSoLuong(),
                nv.getTenNV(),
                nv.getGioiTinh(),
                nv.getNgaySinh(),
                nv.getSoCM(),
                nv.getDienThoai(),
                nv.getTrinhDoHV(),
                nv.getDiaChi(),
                nv.getEmail(),
                nv.getTTHonNhan()
            });
        }
    }

    // phòng ban
    private void loadPB() {
        
        listpb = pbdao.load();
        model = (DefaultTableModel) tbPhongBan.getModel();
        model.setRowCount(0);
        for (PhongBan pb : listpb) {
            model.addRow(new Object[]{
                pb.getMaPB(),
                pb.getTenPB(),
                pb.getTenBoPhan(),
                pb.getNgayThanhLap(),
                pb.getPCChucVu(),
                pb.getSoluong(),
                pb.getGhichu()
            });
        }
    }

    private void loadSearchPB() {
        listpb = pbdao.Search(txtSearchPhongBan.getText());
        model = (DefaultTableModel) tbPhongBan.getModel();
        model.setRowCount(0);
        for (PhongBan phongban : listpb) {
            model.addRow(new Object[]{
                phongban.getMaPB(),
                phongban.getTenPB(),
                phongban.getTenBoPhan(),
                phongban.getNgayThanhLap(),
                phongban.getPCChucVu(),
                phongban.getSoluong(),
                phongban.getGhichu(),});
        }
    }

    ///Lương 
    private void loadLuong() {
        
        model = (DefaultTableModel) tbLuong.getModel();
        model.setRowCount(0);
        List<Object[]> list = tkdao.TKLuong();
        for (Object[] row : list) {
            model.addRow(row);
        }
//        listlg = lgdao.load();
//        model = (DefaultTableModel) tbLuong.getModel();
//        model.setRowCount(0);
//        for (Luong lg : listlg) {
//            model.addRow(new Object[]{
//                lg.getMaNV(),
//                lg.getLuongCB(),
//                lg.getChucDanh(),
//                lg.getChucVu(),
//                lg.getPCChucVu(),
//                lg.getNgayNhap(),
//                lg.getNgaySua(),
//                lg.getGhiChu()
//            });
//        }
//    }
    }
    private void loadSearchLuong() {

        model = (DefaultTableModel) tbLuong.getModel();
        model.setRowCount(0);
        List<Object[]> list = tkdao.TKLuongsearch(txtSearchLuog.getText());
        for (Object[]  lg : list) {
            model.addRow(lg);
        }
    }

    /// hợp đồng
    private void loadHD() {
        listhd = hddao.load();
        model = (DefaultTableModel) tbHopDong.getModel();
        model.setRowCount(0);
        for (HopDong pb : listhd) {
            model.addRow(new Object[]{
                pb.getMaHD(),
                pb.getPhongBan(),
                pb.getNgayBatDau(),
                pb.getMaCV(),
                pb.getHSLuong(),
                pb.getNgayKetThuc(),
                pb.getGhiChu(),});
        }
    }

    private void loadSearchHD() {
        listhd = hddao.Search(txtSearchHopDong.getText());
        model = (DefaultTableModel) tbHopDong.getModel();
        model.setRowCount(0);
        for (HopDong lg : listhd) {
            model.addRow(new Object[]{
                lg.getMaHD(),
                lg.getPhongBan(),
                lg.getNgayBatDau(),
                lg.getMaCV(),
                lg.getHSLuong(),
                lg.getNgayKetThuc(),
                lg.getGhiChu(),});
        }
    }

    //chuc vu
    private void loadCV() {
        listcv = cvdao.load();
        model = (DefaultTableModel) tbChucVu.getModel();
        model.setRowCount(0);
        for (ChucVu cv : listcv) {
            model.addRow(new Object[]{
                cv.getMaCV(),
                cv.getTenCV(),
                cv.getMaNV(),
                cv.getNgayBatDau(),
                cv.getNgayKetThuc(),
                cv.getGhiChu(),});
        }
    }

    private void loadSearchCV() {
        listcv = cvdao.Search(txtSearchCV.getText());
        model = (DefaultTableModel) tbChucVu.getModel();
        model.setRowCount(0);
        for (ChucVu chucvu : listcv) {
            model.addRow(new Object[]{
                chucvu.getMaCV(),
                chucvu.getTenCV(),
                chucvu.getMaNV(),
                chucvu.getNgayBatDau(),
                chucvu.getNgayKetThuc(),
                chucvu.getGhiChu(),});
        }
    }

    // bảo hiểm
    private void loadBH() {
        listbh = bhdao.load();
        model = (DefaultTableModel) tbBaohiem.getModel();
        model.setRowCount(0);
        for (BaoHiem bh : listbh) {
            model.addRow(new Object[]{
                bh.getMaNhanVien(),
                bh.getLoaiBaoHiem(),
                bh.getSoThe(),
                bh.getNgayCap(),
                bh.getNgayHetHan(),
                bh.getNoiCap(),
                bh.getGhiChu(),});
        }
    }

    private void loadSearchBH() {
        listbh = bhdao.Search(txtBHSearch.getText());
        model = (DefaultTableModel) tbBaohiem.getModel();
        model.setRowCount(0);
        for (BaoHiem bh : listbh) {
            model.addRow(new Object[]{
                bh.getMaNhanVien(),
                bh.getLoaiBaoHiem(),
                bh.getSoThe(),
                bh.getNoiCap(),
                bh.getNgayHetHan(),
                bh.getNoiCap(),
                bh.getGhiChu(),});
        }
    }

    // phụ cấp
    private void loadPC() {
        listpc = pcdao.load();
        model = (DefaultTableModel) tbPhuCap.getModel();
        model.setRowCount(0);
        for (PhuCap pc : listpc) {
            model.addRow(new Object[]{
                pc.getMaNhanVien(),
                pc.getLoaiPC(),
                pc.getTienPC(),
                pc.getTuNgay(),
                pc.getDenNgay(),
                pc.getGhichu(),});
        }
    }

    private void loadSearchPC() {
        listpc = pcdao.Search(txtPCSearch.getText());
        model = (DefaultTableModel) tbPhuCap.getModel();
        model.setRowCount(0);
        for (PhuCap pc : listpc) {
            model.addRow(new Object[]{
                pc.getMaNhanVien(),
                pc.getLoaiPC(),
                pc.getTienPC(),
                pc.getTuNgay(),
                pc.getDenNgay(),
                pc.getGhichu(),});
        }
    }
//thuong phat
    
    
     private void loadTP() {
        listtp = tpdao.load();
        model = (DefaultTableModel) tbThuongPhat.getModel();
        model.setRowCount(0);
        for (ThuongPhat tp : listtp) {
            model.addRow(new Object[]{
                tp.getMaNhanVien(),
                tp.getLoaiTP(),
                tp.getTien(),
                tp.getLydo(),
                tp.getNgay(),
                tp.getGhichu(),});
        }
    }
     
    private void loadSearchTP() {
        listtp = tpdao.Search(txtTPSearch.getText());
        model = (DefaultTableModel) tbThuongPhat.getModel();
        model.setRowCount(0);
        for (ThuongPhat tp : listtp) {
            model.addRow(new Object[]{
                tp.getMaNhanVien(),
                tp.getLoaiTP(),
                tp.getTien(),
                tp.getLydo(),
                tp.getNgay(),
                tp.getGhichu(),});
        }}
    
    // Chấm công
    
    private void loadChamCong(){
        listchamcog = chamCongdao.load();
         model = (DefaultTableModel) tbChamCong.getModel();
        model.setRowCount(0);
        for(ChamCong pb:listchamcog){
            model.addRow(new Object[]{
                pb.getMaNhanVien(),
                pb.getNgayCham(),
                pb.getTinhTrang(),
                pb.getPCChucVu(),
                pb.getPCKhac(),
                pb.getSoNgayCong(),
                pb.getSoNgayNghi(),
                pb.getSoGioTangCa(),
                pb.getGhiChu()
            });
        }     
}
    
      public void loadSearchChamCong(){
        listchamcog = chamCongdao.Search(txtSearchchamcong.getText());
          model = (DefaultTableModel)tbChamCong.getModel();
            model.setRowCount(0);
             for (ChamCong chamCog : listchamcog) {
            model.addRow(new Object[]{
                chamCog.getMaNhanVien(),
                chamCog.getNgayCham(),
                chamCog.getTinhTrang(),
                chamCog.getPCChucVu(),
                chamCog.getPCKhac(),
                chamCog.getSoNgayCong(),
                chamCog.getSoNgayNghi(),
                chamCog.getSoGioTangCa(),
                chamCog.getGhiChu()
                
            });
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MNDoiMK;
    private javax.swing.JMenuItem MnDangXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbBaohiem;
    private javax.swing.JTable tbChamCong;
    private javax.swing.JTable tbChucVu;
    private javax.swing.JTable tbHopDong;
    private javax.swing.JTable tbLuong;
    private javax.swing.JTable tbNhanvien;
    private javax.swing.JTable tbPhongBan;
    private javax.swing.JTable tbPhuCap;
    private javax.swing.JTable tbThuongPhat;
    private javax.swing.JInternalFrame test;
    private javax.swing.JTextField txtBHSearch;
    private javax.swing.JTextField txtPCSearch;
    private javax.swing.JLabel txtQuyen;
    private javax.swing.JTextField txtSearchCV;
    private javax.swing.JTextField txtSearchHopDong;
    private javax.swing.JTextField txtSearchLuog;
    private javax.swing.JTextField txtSearchNhanSu;
    private javax.swing.JTextField txtSearchPhongBan;
    private javax.swing.JTextField txtSearchchamcong;
    private javax.swing.JTextField txtTPSearch;
    // End of variables declaration//GEN-END:variables
}
